name: Deployment pipeline
permissions:
  contents: write

on:
  push:
    branches:
      - main


jobs:
  deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - name: Deploy 
        uses: JamesIves/github-pages-deploy-action@v4
        with: 
          folder: build